### ISSUE TITLE
根据统一接口定义自动生成补全库（以及文档？）

### ISSUE THREAD

**Issue by yqs112358** [LiteLDev/LeviScript#7]
LLSE在引擎层采用跨语言统一接口设计，但是不同语言后端的补全库需要单独手动维护（js/lua/py），工作量较大且容易出现遗漏。另外文档编写和修改也较为麻烦。

**设想：** 使用某种统一接口定义语言（如TypeScript接口）对所有API进行建模，然后写程序解析AST并翻译到各目标语言的补全文件。以后变动API时，除了修改代码之外，只需要对接口文件进行修改，并执行程序更新补全库即可（可由github actions自动化）

另外如果可能的话，在接口文件中嵌入文本段，并用于自动化生成文档，以降低文档维护工作量

**Comment by cvxz8** [comment]
感觉涉及到复杂类型时，难以进行翻译
例如Typescript中的交叉、联合类型、keyof、typeof、条件类型、类型推断，难以在python中表示

**Comment by harry-xi** [comment]
假定这个API建模手动完成，或许考虑选取一个与特定语言无关的形式来提供这个内容。
这样子，对与一些复杂类型，我们可以采取类似下面这个形式。同时，这么做或许可以更易于解析和处理
```toml
[class]
docs = '''
文档
'''
# 选择toml举例是因为它的多行字符串功能会文档内嵌提供不小的便利
[class.methodsA]
 # 一个带有复杂类型声明的方法
docs = '''
文档内容
'''
type.ts = ""
type.py = ""
type.lua = ""
# 把这些字符分别替换给对应语言
[class.methodsB]
# 一个简单的类型声明
docs='''
文档内容
'''
type=""
# 这里或许应该采取别的形式，而非字符串，但是我暂时没有进一步的思考
```
一个额外的思考，有没有那个语言从声明文件生成的文档可以直接满足ls项目文档的需求，他们通常会提供一些极有价值的功能
（虽然似乎如果需要，我们可以在自己实现文档生成的时候自己实现那些功能

**另外一个问题，我们有多大可能自动化的从源码生成API类型声明。**
